name: check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout node
        uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-node@v3
      - name: install dependencies
        run: npm install
      - name: lint
        run: npm run lint